# Analysis of Cost

In [3]:
import pandas as pd
import datetime

Cost_Data_Fy = 'Data_Cost_Fy-CVX.csv'
Cash_Data_Fy = 'Data_Cash_Flow_Fy-CVX.csv'
today = datetime.date.today()

# Waterfall Analysis of Cost

In [4]:
cost_df = pd.read_csv(Cost_Data_Fy,index_col='FiscalYear')
cost_df['CogsMargin'] = round(cost_df['COGS'] / cost_df['Revenue'], 2)
cost_df['SgaMargin'] = round(cost_df['SGA'] / cost_df['Revenue'], 2)
cost_df['RndMargin'] = round(cost_df['RND'] / cost_df['Revenue'], 2)
cost_df['OperatingMargin'] = round(cost_df['OperatingExpense'] / cost_df['Revenue'], 2)
cost_df['CapexMargin'] = round(cost_df['CAPEX'].abs() / cost_df['Revenue'], 2)


cost_df

,Revenue,COGS,SGA,RND,OperatingExpense,TaxPaid,CAPEX,CogsMargin,SgaMargin,RndMargin,OperatingMargin,CapexMargin
FiscalYear,,,,,,,,,,,,
1992,39271.0,19872.0,1761.0,0.0,9761.0,-1253.0,-3352.0,0.51,0.04,0.00,0.25,0.09
1993,36642.0,18007.0,1530.0,0.0,9228.0,-1161.0,-3323.0,0.49,0.04,0.00,0.25,0.09
1994,35854.0,16990.0,963.0,379.0,15715.0,-1110.0,-3405.0,0.47,0.03,0.01,0.44,0.09
1995,37082.0,18033.0,1384.0,372.0,16859.0,-859.0,-3529.0,0.49,0.04,0.01,0.45,0.10
1996,43893.0,22826.0,1377.0,455.0,15963.0,-2133.0,-3424.0,0.52,0.03,0.01,0.36,0.08
1997,41950.0,20223.0,1533.0,493.0,15913.0,-2246.0,-3899.0,0.48,0.04,0.01,0.38,0.09
1998,30557.0,14036.0,2239.0,478.0,14282.0,-495.0,-3880.0,0.46,0.07,0.02,0.47,0.13
1999,85713.0,55101.0,3222.0,0.0,17568.0,-2565.0,-7895.0,0.64,0.04,0.00,0.20,0.09
2000,119130.0,79086.0,3626.0,0.0,18173.0,-6322.0,-7629.0,0.66,0.03,0.00,0.15,0.06
2001,106245.0,69238.0,3984.0,0.0,19653.0,-4360.0,-9713.0,0.65,0.04,0.00,0.18,0.09
2002,98537.0,65437.0,4155.0,0.0,19000.0,-2998.0,-7597.0,0.66,0.04,0.00,0.19,0.08
2003,121277.0,80380.0,4440.0,0.0,20572.0,-5294.0,-5625.0,0.66,0.04,0.00,0.17,0.05
2004,155300.0,104948.0,4557.0,0.0,21342.0,-7517.0,-6310.0,0.68,0.03,0.00,0.14,0.04
2005,198200.0,140902.0,4828.0,0.0,22804.0,-11098.0,-8701.0,0.71,0.02,0.00,0.12,0.04
2006,210118.0,144139.0,5093.0,0.0,33482.0,-14838.0,-13813.0,0.69,0.02,0.00,0.16,0.07
2007,220904.0,151564.0,5926.0,0.0,36900.0,-13479.0,-16678.0,0.69,0.03,0.00,0.17,0.08
2008,267639.0,192192.0,5756.0,0.0,37756.0,-19026.0,-19666.0,0.72,0.02,0.00,0.14,0.07
2009,168320.0,125619.0,4527.0,0.0,35570.0,-7965.0,-19843.0,0.75,0.03,0.00,0.21,0.12
2010,198198.0,129530.0,4767.0,0.0,43293.0,-12919.0,-19612.0,0.65,0.02,0.00,0.22,0.10
2011,244371.0,162834.0,4745.0,0.0,43238.0,-20626.0,-26500.0,0.67,0.02,0.00,0.18,0.11
2012,230590.0,154179.0,4724.0,0.0,41398.0,-19996.0,-30938.0,0.67,0.02,0.00,0.18,0.13
2013,220156.0,148882.0,4510.0,0.0,44061.0,-14308.0,-37985.0,0.68,0.02,0.00,0.20,0.17
2014,200494.0,136464.0,4494.0,0.0,44304.0,-11892.0,-35407.0,0.68,0.02,0.00,0.22,0.18
2015,129925.0,90788.0,4443.0,0.0,42847.0,-132.0,-29504.0,0.70,0.03,0.00,0.33,0.23
2016,110215.0,78778.0,4305.0,0.0,36908.0,1729.0,-18109.0,0.71,0.04,0.00,0.33,0.16
2017,134674.0,95114.0,4110.0,0.0,36432.0,48.0,-13404.0,0.71,0.03,0.00,0.27,0.10
2018,158902.0,113997.0,3838.0,0.0,30459.0,-5715.0,-13792.0,0.72,0.02,0.00,0.19,0.09
2019,139865.0,109331.0,4143.0,0.0,30434.0,-2691.0,-14116.0,0.78,0.03,0.00,0.22,0.10
2020,94471.0,71656.0,4213.0,0.0,28912.0,1892.0,-8922.0,0.76,0.04,0.00,0.31,0.09
2021,155606.0,110174.0,4014.0,0.0,29252.0,-5950.0,-8056.0,0.71,0.03,0.00,0.19,0.05
2022,235717.0,161735.0,4312.0,0.0,34032.0,-14066.0,-11974.0,0.69,0.02,0.00,0.14,0.05
2023,196913.0,136522.0,4141.0,0.0,34162.0,-8173.0,-15829.0,0.69,0.02,0.00,0.17,0.08

In [5]:
oe_df = cost_df[['Revenue', 'COGS', 'CogsMargin', 'SGA', 'SgaMargin', 'RND', 'RndMargin', 'OperatingExpense', 'OperatingMargin']]

oe_df

,Revenue,COGS,CogsMargin,SGA,SgaMargin,RND,RndMargin,OperatingExpense,OperatingMargin
FiscalYear,,,,,,,,,
1992,39271.0,19872.0,0.51,1761.0,0.04,0.0,0.00,9761.0,0.25
1993,36642.0,18007.0,0.49,1530.0,0.04,0.0,0.00,9228.0,0.25
1994,35854.0,16990.0,0.47,963.0,0.03,379.0,0.01,15715.0,0.44
1995,37082.0,18033.0,0.49,1384.0,0.04,372.0,0.01,16859.0,0.45
1996,43893.0,22826.0,0.52,1377.0,0.03,455.0,0.01,15963.0,0.36
1997,41950.0,20223.0,0.48,1533.0,0.04,493.0,0.01,15913.0,0.38
1998,30557.0,14036.0,0.46,2239.0,0.07,478.0,0.02,14282.0,0.47
1999,85713.0,55101.0,0.64,3222.0,0.04,0.0,0.00,17568.0,0.20
2000,119130.0,79086.0,0.66,3626.0,0.03,0.0,0.00,18173.0,0.15
2001,106245.0,69238.0,0.65,3984.0,0.04,0.0,0.00,19653.0,0.18
2002,98537.0,65437.0,0.66,4155.0,0.04,0.0,0.00,19000.0,0.19
2003,121277.0,80380.0,0.66,4440.0,0.04,0.0,0.00,20572.0,0.17
2004,155300.0,104948.0,0.68,4557.0,0.03,0.0,0.00,21342.0,0.14
2005,198200.0,140902.0,0.71,4828.0,0.02,0.0,0.00,22804.0,0.12
2006,210118.0,144139.0,0.69,5093.0,0.02,0.0,0.00,33482.0,0.16
2007,220904.0,151564.0,0.69,5926.0,0.03,0.0,0.00,36900.0,0.17
2008,267639.0,192192.0,0.72,5756.0,0.02,0.0,0.00,37756.0,0.14
2009,168320.0,125619.0,0.75,4527.0,0.03,0.0,0.00,35570.0,0.21
2010,198198.0,129530.0,0.65,4767.0,0.02,0.0,0.00,43293.0,0.22
2011,244371.0,162834.0,0.67,4745.0,0.02,0.0,0.00,43238.0,0.18
2012,230590.0,154179.0,0.67,4724.0,0.02,0.0,0.00,41398.0,0.18
2013,220156.0,148882.0,0.68,4510.0,0.02,0.0,0.00,44061.0,0.20
2014,200494.0,136464.0,0.68,4494.0,0.02,0.0,0.00,44304.0,0.22
2015,129925.0,90788.0,0.70,4443.0,0.03,0.0,0.00,42847.0,0.33
2016,110215.0,78778.0,0.71,4305.0,0.04,0.0,0.00,36908.0,0.33
2017,134674.0,95114.0,0.71,4110.0,0.03,0.0,0.00,36432.0,0.27
2018,158902.0,113997.0,0.72,3838.0,0.02,0.0,0.00,30459.0,0.19
2019,139865.0,109331.0,0.78,4143.0,0.03,0.0,0.00,30434.0,0.22
2020,94471.0,71656.0,0.76,4213.0,0.04,0.0,0.00,28912.0,0.31
2021,155606.0,110174.0,0.71,4014.0,0.03,0.0,0.00,29252.0,0.19
2022,235717.0,161735.0,0.69,4312.0,0.02,0.0,0.00,34032.0,0.14
2023,196913.0,136522.0,0.69,4141.0,0.02,0.0,0.00,34162.0,0.17

In [6]:
capex_df = cost_df[['CAPEX', 'CapexMargin']]

capex_df

              CAPEX  CapexMargin
FiscalYear
1992        -3352.0         0.09
1993        -3323.0         0.09
1994        -3405.0         0.09
1995        -3529.0         0.10
1996        -3424.0         0.08
1997        -3899.0         0.09
1998        -3880.0         0.13
1999        -7895.0         0.09
2000        -7629.0         0.06
2001        -9713.0         0.09
2002        -7597.0         0.08
2003        -5625.0         0.05
2004        -6310.0         0.04
2005        -8701.0         0.04
2006       -13813.0         0.07
2007       -16678.0         0.08
2008       -19666.0         0.07
2009       -19843.0         0.12
2010       -19612.0         0.10
2011       -26500.0         0.11
2012       -30938.0         0.13
2013       -37985.0         0.17
2014       -35407.0         0.18
2015       -29504.0         0.23
2016       -18109.0         0.16
2017       -13404.0         0.10
2018       -13792.0         0.09
2019       -14116.0         0.10
2020        -8922.0         0.09
2021        -8056.0         0.05
2022       -11974.0         0.05
2023       -15829.0         0.08

In [7]:
tax_df = cost_df [['TaxPaid']].abs()
cash_df = pd.read_csv(Cash_Data_Fy,index_col='FiscalYear')
tax_df['NetIncome'] = cash_df['NetIncome']
tax_df['TaxRate'] = round(tax_df['TaxPaid'] / tax_df['NetIncome'], 2)


tax_df

            TaxPaid  NetIncome  TaxRate
FiscalYear
1992         1253.0     1569.0     0.80
1993         1161.0     1265.0     0.92
1994         1110.0     1693.0     0.66
1995          859.0      930.0     0.92
1996         2133.0     2607.0     0.82
1997         2246.0     3256.0     0.69
1998          495.0     1339.0     0.37
1999         2565.0     3247.0     0.79
2000         6322.0     7727.0     0.82
2001         4360.0     3288.0     1.33
2002         2998.0     1132.0     2.65
2003         5294.0     7230.0     0.73
2004         7517.0    13328.0     0.56
2005        11098.0    14099.0     0.79
2006        14838.0    17138.0     0.87
2007        13479.0    18688.0     0.72
2008        19026.0    23931.0     0.80
2009         7965.0    10483.0     0.76
2010        12919.0    19024.0     0.68
2011        20626.0    26895.0     0.77
2012        19996.0    26179.0     0.76
2013        14308.0    21423.0     0.67
2014        11892.0    19241.0     0.62
2015          132.0     4587.0     0.03
2016         1729.0     -497.0    -3.48
2017           48.0     9195.0     0.01
2018         5715.0    14824.0     0.39
2019         2691.0     2924.0     0.92
2020         1892.0    -5543.0    -0.34
2021         5950.0    15625.0     0.38
2022        14066.0    35465.0     0.40
2023         8173.0    21369.0     0.38