# Analysis of Cash Flow

In [1]:
import pandas as pd
import datetime

Cash_Data_Fy = 'Data_Cash_Flow_Fy-CVX.csv'
today = datetime.date.today()

# Waterfall Analysis of Cash Flow

In [2]:
cash_df = pd.read_csv(Cash_Data_Fy,index_col='FiscalYear')
cash_df['GrossProfitMargin'] = round(cash_df['GrossProfit'] / cash_df['Revenue'], 2)
cash_df['OpIncMargin'] = round(cash_df['OperatingIncome'] / cash_df['Revenue'], 2)
cash_df['NetIncMargin'] = round(cash_df['NetIncome'] / cash_df['Revenue'], 2)
cash_df['CashFromOpsMargin'] = round(cash_df['CashFromOperations'] / cash_df['Revenue'], 2)
cash_df['FcfMargin'] = round(cash_df['FreeCashFlow'] / cash_df['Revenue'], 2)


cash_df

,Revenue,GrossProfit,OperatingIncome,NetIncome,CashFromOperations,FreeCashFlow,GrossProfitMargin,OpIncMargin,NetIncMargin,CashFromOpsMargin,FcfMargin
FiscalYear,,,,,,,,,,,
1992,39271.0,19399.0,9638.0,1569.0,3914.0,562.0,0.49,0.25,0.04,0.10,0.01
1993,36642.0,18635.0,9407.0,1265.0,4221.0,898.0,0.51,0.26,0.03,0.12,0.02
1994,35854.0,18864.0,3149.0,1693.0,2896.0,-509.0,0.53,0.09,0.05,0.08,-0.01
1995,37082.0,19049.0,2190.0,930.0,4075.0,546.0,0.51,0.06,0.03,0.11,0.01
1996,43893.0,21067.0,5104.0,2607.0,5797.0,2373.0,0.48,0.12,0.06,0.13,0.05
1997,41950.0,21727.0,5814.0,3256.0,4583.0,684.0,0.52,0.14,0.08,0.11,0.02
1998,30557.0,16521.0,2239.0,1339.0,3731.0,-149.0,0.54,0.07,0.04,0.12,-0.00
1999,85713.0,30612.0,13044.0,3247.0,7771.0,-124.0,0.36,0.15,0.04,0.09,-0.00
2000,119130.0,40044.0,21871.0,7727.0,13467.0,5838.0,0.34,0.18,0.06,0.11,0.05
2001,106245.0,37007.0,17354.0,3288.0,11457.0,1744.0,0.35,0.16,0.03,0.11,0.02
2002,98537.0,33100.0,14100.0,1132.0,9943.0,2346.0,0.34,0.14,0.01,0.10,0.02
2003,121277.0,40897.0,20325.0,7230.0,12315.0,6690.0,0.34,0.17,0.06,0.10,0.06
2004,155300.0,50352.0,29010.0,13328.0,14690.0,8380.0,0.32,0.19,0.09,0.09,0.05
2005,198200.0,57298.0,34494.0,14099.0,20105.0,11404.0,0.29,0.17,0.07,0.10,0.06
2006,210118.0,65979.0,32497.0,17138.0,24323.0,10510.0,0.31,0.15,0.08,0.12,0.05
2007,220904.0,69340.0,32440.0,18688.0,24977.0,8299.0,0.31,0.15,0.08,0.11,0.04
2008,267639.0,75447.0,37691.0,23931.0,29632.0,9966.0,0.28,0.14,0.09,0.11,0.04
2009,168320.0,42701.0,7131.0,10483.0,19373.0,-470.0,0.25,0.04,0.06,0.12,-0.00
2010,198198.0,68668.0,25375.0,19024.0,31354.0,11742.0,0.35,0.13,0.10,0.16,0.06
2011,244371.0,81537.0,38299.0,26895.0,41095.0,14595.0,0.33,0.16,0.11,0.17,0.06
2012,230590.0,76411.0,35013.0,26179.0,38812.0,7874.0,0.33,0.15,0.11,0.17,0.03
2013,220156.0,71274.0,27213.0,21423.0,35002.0,-2983.0,0.32,0.12,0.10,0.16,-0.01
2014,200494.0,64030.0,19726.0,19241.0,31475.0,-3932.0,0.32,0.10,0.10,0.16,-0.02
2015,129925.0,39137.0,-3710.0,4587.0,19456.0,-10048.0,0.30,-0.03,0.04,0.15,-0.08
2016,110215.0,31437.0,-5471.0,-497.0,12690.0,-5419.0,0.29,-0.05,-0.00,0.12,-0.05
2017,134674.0,39560.0,3128.0,9195.0,20338.0,6934.0,0.29,0.02,0.07,0.15,0.05
2018,158902.0,44905.0,14446.0,14824.0,30618.0,16826.0,0.28,0.09,0.09,0.19,0.11
2019,139865.0,30534.0,100.0,2924.0,27314.0,13198.0,0.22,0.00,0.02,0.20,0.09
2020,94471.0,22815.0,-6097.0,-5543.0,10577.0,1655.0,0.24,-0.06,-0.06,0.11,0.02
2021,155606.0,45432.0,16180.0,15625.0,29187.0,21131.0,0.29,0.10,0.10,0.19,0.14
2022,235717.0,73982.0,39950.0,35465.0,49602.0,37628.0,0.31,0.17,0.15,0.21,0.16
2023,196913.0,60391.0,26229.0,21369.0,35609.0,19780.0,0.31,0.13,0.11,0.18,0.10

In [3]:
gpm_df = cash_df[['Revenue', 'GrossProfit', 'GrossProfitMargin', 'OperatingIncome', 'OpIncMargin', 'NetIncome', 'NetIncMargin']]


gpm_df

,Revenue,GrossProfit,GrossProfitMargin,OperatingIncome,OpIncMargin,NetIncome,NetIncMargin
FiscalYear,,,,,,,
1992,39271.0,19399.0,0.49,9638.0,0.25,1569.0,0.04
1993,36642.0,18635.0,0.51,9407.0,0.26,1265.0,0.03
1994,35854.0,18864.0,0.53,3149.0,0.09,1693.0,0.05
1995,37082.0,19049.0,0.51,2190.0,0.06,930.0,0.03
1996,43893.0,21067.0,0.48,5104.0,0.12,2607.0,0.06
1997,41950.0,21727.0,0.52,5814.0,0.14,3256.0,0.08
1998,30557.0,16521.0,0.54,2239.0,0.07,1339.0,0.04
1999,85713.0,30612.0,0.36,13044.0,0.15,3247.0,0.04
2000,119130.0,40044.0,0.34,21871.0,0.18,7727.0,0.06
2001,106245.0,37007.0,0.35,17354.0,0.16,3288.0,0.03
2002,98537.0,33100.0,0.34,14100.0,0.14,1132.0,0.01
2003,121277.0,40897.0,0.34,20325.0,0.17,7230.0,0.06
2004,155300.0,50352.0,0.32,29010.0,0.19,13328.0,0.09
2005,198200.0,57298.0,0.29,34494.0,0.17,14099.0,0.07
2006,210118.0,65979.0,0.31,32497.0,0.15,17138.0,0.08
2007,220904.0,69340.0,0.31,32440.0,0.15,18688.0,0.08
2008,267639.0,75447.0,0.28,37691.0,0.14,23931.0,0.09
2009,168320.0,42701.0,0.25,7131.0,0.04,10483.0,0.06
2010,198198.0,68668.0,0.35,25375.0,0.13,19024.0,0.10
2011,244371.0,81537.0,0.33,38299.0,0.16,26895.0,0.11
2012,230590.0,76411.0,0.33,35013.0,0.15,26179.0,0.11
2013,220156.0,71274.0,0.32,27213.0,0.12,21423.0,0.10
2014,200494.0,64030.0,0.32,19726.0,0.10,19241.0,0.10
2015,129925.0,39137.0,0.30,-3710.0,-0.03,4587.0,0.04
2016,110215.0,31437.0,0.29,-5471.0,-0.05,-497.0,-0.00
2017,134674.0,39560.0,0.29,3128.0,0.02,9195.0,0.07
2018,158902.0,44905.0,0.28,14446.0,0.09,14824.0,0.09
2019,139865.0,30534.0,0.22,100.0,0.00,2924.0,0.02
2020,94471.0,22815.0,0.24,-6097.0,-0.06,-5543.0,-0.06
2021,155606.0,45432.0,0.29,16180.0,0.10,15625.0,0.10
2022,235717.0,73982.0,0.31,39950.0,0.17,35465.0,0.15
2023,196913.0,60391.0,0.31,26229.0,0.13,21369.0,0.11

In [4]:
fcf_df = cash_df[['Revenue', 'CashFromOperations' ,'CashFromOpsMargin' ,'FreeCashFlow', 'FcfMargin']]

fcf_df

,Revenue,CashFromOperations,CashFromOpsMargin,FreeCashFlow,FcfMargin
FiscalYear,,,,,
1992,39271.0,3914.0,0.10,562.0,0.01
1993,36642.0,4221.0,0.12,898.0,0.02
1994,35854.0,2896.0,0.08,-509.0,-0.01
1995,37082.0,4075.0,0.11,546.0,0.01
1996,43893.0,5797.0,0.13,2373.0,0.05
1997,41950.0,4583.0,0.11,684.0,0.02
1998,30557.0,3731.0,0.12,-149.0,-0.00
1999,85713.0,7771.0,0.09,-124.0,-0.00
2000,119130.0,13467.0,0.11,5838.0,0.05
2001,106245.0,11457.0,0.11,1744.0,0.02
2002,98537.0,9943.0,0.10,2346.0,0.02
2003,121277.0,12315.0,0.10,6690.0,0.06
2004,155300.0,14690.0,0.09,8380.0,0.05
2005,198200.0,20105.0,0.10,11404.0,0.06
2006,210118.0,24323.0,0.12,10510.0,0.05
2007,220904.0,24977.0,0.11,8299.0,0.04
2008,267639.0,29632.0,0.11,9966.0,0.04
2009,168320.0,19373.0,0.12,-470.0,-0.00
2010,198198.0,31354.0,0.16,11742.0,0.06
2011,244371.0,41095.0,0.17,14595.0,0.06
2012,230590.0,38812.0,0.17,7874.0,0.03
2013,220156.0,35002.0,0.16,-2983.0,-0.01
2014,200494.0,31475.0,0.16,-3932.0,-0.02
2015,129925.0,19456.0,0.15,-10048.0,-0.08
2016,110215.0,12690.0,0.12,-5419.0,-0.05
2017,134674.0,20338.0,0.15,6934.0,0.05
2018,158902.0,30618.0,0.19,16826.0,0.11
2019,139865.0,27314.0,0.20,13198.0,0.09
2020,94471.0,10577.0,0.11,1655.0,0.02
2021,155606.0,29187.0,0.19,21131.0,0.14
2022,235717.0,49602.0,0.21,37628.0,0.16
2023,196913.0,35609.0,0.18,19780.0,0.10