# Analysis of Cost

In [1]:
import pandas as pd
import datetime

Cost_Data_Fy = 'Data_Cost_Fy-XOM.csv'
Cash_Data_Fy = 'Data_Cash_Flow_Fy-XOM.csv'
today = datetime.date.today()

# Waterfall Analysis of Cost

In [2]:
cost_df = pd.read_csv(Cost_Data_Fy,index_col='FiscalYear')
cost_df['CogsMargin'] = round(cost_df['COGS'] / cost_df['Revenue'], 2)
cost_df['SgaMargin'] = round(cost_df['SGA'] / cost_df['Revenue'], 2)
cost_df['RndMargin'] = round(cost_df['RND'] / cost_df['Revenue'], 2)
cost_df['OperatingMargin'] = round(cost_df['OperatingExpense'] / cost_df['Revenue'], 2)
cost_df['CapexMargin'] = round(cost_df['CAPEX'].abs() / cost_df['Revenue'], 2)


cost_df

,Revenue,COGS,SGA,RND,OperatingExpense,TaxPaid,CAPEX,CogsMargin,SgaMargin,RndMargin,OperatingMargin,CapexMargin
FiscalYear,,,,,,,,,,,,
1984,90854.0,58865.0,6334.0,0.0,22197.0,-5070.0,0.0,0.65,0.07,0.0,0.24,0.00
1985,86673.0,55733.0,4824.0,0.0,20817.0,-4688.0,0.0,0.64,0.06,0.0,0.24,0.00
1986,69888.0,39316.0,5230.0,0.0,22721.0,-3196.0,0.0,0.56,0.07,0.0,0.33,0.00
1987,76416.0,44429.0,5621.0,0.0,24979.0,-2703.0,0.0,0.58,0.07,0.0,0.33,0.00
1988,79557.0,44505.0,5824.0,0.0,26765.0,-3124.0,0.0,0.56,0.07,0.0,0.34,0.00
1989,86656.0,50675.0,6398.0,0.0,28017.0,-2028.0,-6313.0,0.58,0.07,0.0,0.32,0.07
1990,105519.0,63698.0,7776.0,0.0,33215.0,-3170.0,-6548.0,0.60,0.07,0.0,0.31,0.06
1991,102847.0,61248.0,7881.0,0.0,33528.0,-2918.0,-7324.0,0.60,0.08,0.0,0.33,0.07
1992,103160.0,62287.0,7432.0,0.0,33989.0,-2477.0,-7225.0,0.60,0.07,0.0,0.33,0.07
1993,97825.0,58883.0,7009.0,0.0,31638.0,-2772.0,-6956.0,0.60,0.07,0.0,0.32,0.07
1994,99683.0,59224.0,7226.0,0.0,33425.0,-2704.0,-6643.0,0.59,0.07,0.0,0.34,0.07
1995,107893.0,62352.0,7629.0,0.0,36343.0,-3972.0,-7128.0,0.58,0.07,0.0,0.34,0.07
1996,116728.0,70424.0,7961.0,0.0,36246.0,-4406.0,-7209.0,0.60,0.07,0.0,0.31,0.06
1997,176552.0,104168.0,13574.0,0.0,55669.0,-7605.0,-11652.0,0.59,0.08,0.0,0.32,0.07
1998,165627.0,81317.0,12925.0,0.0,75409.0,-3939.0,-12730.0,0.49,0.08,0.0,0.46,0.08
1999,182529.0,95063.0,13134.0,0.0,77849.0,-3240.0,-10849.0,0.52,0.07,0.0,0.43,0.06
2000,231846.0,127449.0,12044.0,0.0,52753.0,-11075.0,-8446.0,0.55,0.05,0.0,0.23,0.04
2001,212785.0,111175.0,12898.0,0.0,54123.0,-8967.0,-9989.0,0.52,0.06,0.0,0.25,0.05
2002,204506.0,109701.0,12356.0,0.0,54238.0,-6499.0,-11437.0,0.54,0.06,0.0,0.27,0.06
2003,246738.0,129928.0,13396.0,0.0,60088.0,-11006.0,-12859.0,0.53,0.05,0.0,0.24,0.05
2004,298035.0,163547.0,13849.0,0.0,91833.0,-15911.0,-11986.0,0.55,0.05,0.0,0.31,0.04
2005,370680.0,213002.0,14402.0,0.0,96951.0,-23302.0,-13839.0,0.57,0.04,0.0,0.26,0.04
2006,377635.0,213255.0,14273.0,0.0,64892.0,-27902.0,-15462.0,0.56,0.04,0.0,0.17,0.04
2007,395651.0,231383.0,14890.0,0.0,101290.0,-29864.0,-15387.0,0.58,0.04,0.0,0.26,0.04
2008,466278.0,287359.0,15873.0,0.0,105930.0,-36530.0,-19318.0,0.62,0.03,0.0,0.23,0.04
2009,303443.0,211769.0,14735.0,0.0,63492.0,-15119.0,-22491.0,0.70,0.05,0.0,0.21,0.07
2010,370125.0,277058.0,14683.0,0.0,52945.0,-21561.0,-26871.0,0.75,0.04,0.0,0.14,0.07
2011,467029.0,355888.0,14983.0,0.0,57037.0,-31051.0,-30975.0,0.76,0.03,0.0,0.12,0.07
2012,451509.0,350353.0,13877.0,0.0,51275.0,-31045.0,-34271.0,0.78,0.03,0.0,0.11,0.08
2013,420836.0,332452.0,12877.0,0.0,48083.0,-24263.0,-33669.0,0.79,0.03,0.0,0.11,0.08
2014,394105.0,313470.0,12598.0,0.0,46553.0,-18015.0,-32952.0,0.80,0.03,0.0,0.12,0.08
2015,239854.0,183638.0,11501.0,0.0,43333.0,-5415.0,-26490.0,0.77,0.05,0.0,0.18,0.11
2016,200628.0,156927.0,12278.0,0.0,42765.0,406.0,-16163.0,0.78,0.06,0.0,0.21,0.08
2017,237162.0,180800.0,12394.0,0.0,44288.0,1174.0,-15402.0,0.76,0.05,0.0,0.19,0.06
2018,279332.0,211599.0,12765.0,0.0,46894.0,-9532.0,-19574.0,0.76,0.05,0.0,0.17,0.07
2019,255583.0,199625.0,12633.0,0.0,44427.0,-5282.0,-24361.0,0.78,0.05,0.0,0.17,0.10
2020,178574.0,170447.0,11373.0,0.0,38780.0,5632.0,-17282.0,0.95,0.06,0.0,0.22,0.10
2021,276692.0,211806.0,10360.0,0.0,41653.0,-7636.0,-12076.0,0.77,0.04,0.0,0.15,0.04
2022,398675.0,295608.0,10577.0,0.0,39521.0,-20176.0,-18407.0,0.74,0.03,0.0,0.10,0.05
2023,334697.0,250555.0,10633.0,0.0,40395.0,-15429.0,-21919.0,0.75,0.03,0.0,0.12,0.07

In [3]:
oe_df = cost_df[['Revenue', 'COGS', 'CogsMargin', 'SGA', 'SgaMargin', 'RND', 'RndMargin', 'OperatingExpense', 'OperatingMargin']]

oe_df

,Revenue,COGS,CogsMargin,SGA,SgaMargin,RND,RndMargin,OperatingExpense,OperatingMargin
FiscalYear,,,,,,,,,
1984,90854.0,58865.0,0.65,6334.0,0.07,0.0,0.0,22197.0,0.24
1985,86673.0,55733.0,0.64,4824.0,0.06,0.0,0.0,20817.0,0.24
1986,69888.0,39316.0,0.56,5230.0,0.07,0.0,0.0,22721.0,0.33
1987,76416.0,44429.0,0.58,5621.0,0.07,0.0,0.0,24979.0,0.33
1988,79557.0,44505.0,0.56,5824.0,0.07,0.0,0.0,26765.0,0.34
1989,86656.0,50675.0,0.58,6398.0,0.07,0.0,0.0,28017.0,0.32
1990,105519.0,63698.0,0.60,7776.0,0.07,0.0,0.0,33215.0,0.31
1991,102847.0,61248.0,0.60,7881.0,0.08,0.0,0.0,33528.0,0.33
1992,103160.0,62287.0,0.60,7432.0,0.07,0.0,0.0,33989.0,0.33
1993,97825.0,58883.0,0.60,7009.0,0.07,0.0,0.0,31638.0,0.32
1994,99683.0,59224.0,0.59,7226.0,0.07,0.0,0.0,33425.0,0.34
1995,107893.0,62352.0,0.58,7629.0,0.07,0.0,0.0,36343.0,0.34
1996,116728.0,70424.0,0.60,7961.0,0.07,0.0,0.0,36246.0,0.31
1997,176552.0,104168.0,0.59,13574.0,0.08,0.0,0.0,55669.0,0.32
1998,165627.0,81317.0,0.49,12925.0,0.08,0.0,0.0,75409.0,0.46
1999,182529.0,95063.0,0.52,13134.0,0.07,0.0,0.0,77849.0,0.43
2000,231846.0,127449.0,0.55,12044.0,0.05,0.0,0.0,52753.0,0.23
2001,212785.0,111175.0,0.52,12898.0,0.06,0.0,0.0,54123.0,0.25
2002,204506.0,109701.0,0.54,12356.0,0.06,0.0,0.0,54238.0,0.27
2003,246738.0,129928.0,0.53,13396.0,0.05,0.0,0.0,60088.0,0.24
2004,298035.0,163547.0,0.55,13849.0,0.05,0.0,0.0,91833.0,0.31
2005,370680.0,213002.0,0.57,14402.0,0.04,0.0,0.0,96951.0,0.26
2006,377635.0,213255.0,0.56,14273.0,0.04,0.0,0.0,64892.0,0.17
2007,395651.0,231383.0,0.58,14890.0,0.04,0.0,0.0,101290.0,0.26
2008,466278.0,287359.0,0.62,15873.0,0.03,0.0,0.0,105930.0,0.23
2009,303443.0,211769.0,0.70,14735.0,0.05,0.0,0.0,63492.0,0.21
2010,370125.0,277058.0,0.75,14683.0,0.04,0.0,0.0,52945.0,0.14
2011,467029.0,355888.0,0.76,14983.0,0.03,0.0,0.0,57037.0,0.12
2012,451509.0,350353.0,0.78,13877.0,0.03,0.0,0.0,51275.0,0.11
2013,420836.0,332452.0,0.79,12877.0,0.03,0.0,0.0,48083.0,0.11
2014,394105.0,313470.0,0.80,12598.0,0.03,0.0,0.0,46553.0,0.12
2015,239854.0,183638.0,0.77,11501.0,0.05,0.0,0.0,43333.0,0.18
2016,200628.0,156927.0,0.78,12278.0,0.06,0.0,0.0,42765.0,0.21
2017,237162.0,180800.0,0.76,12394.0,0.05,0.0,0.0,44288.0,0.19
2018,279332.0,211599.0,0.76,12765.0,0.05,0.0,0.0,46894.0,0.17
2019,255583.0,199625.0,0.78,12633.0,0.05,0.0,0.0,44427.0,0.17
2020,178574.0,170447.0,0.95,11373.0,0.06,0.0,0.0,38780.0,0.22
2021,276692.0,211806.0,0.77,10360.0,0.04,0.0,0.0,41653.0,0.15
2022,398675.0,295608.0,0.74,10577.0,0.03,0.0,0.0,39521.0,0.10
2023,334697.0,250555.0,0.75,10633.0,0.03,0.0,0.0,40395.0,0.12

In [4]:
capex_df = cost_df[['CAPEX', 'CapexMargin']]

capex_df

              CAPEX  CapexMargin
FiscalYear
1984            0.0         0.00
1985            0.0         0.00
1986            0.0         0.00
1987            0.0         0.00
1988            0.0         0.00
1989        -6313.0         0.07
1990        -6548.0         0.06
1991        -7324.0         0.07
1992        -7225.0         0.07
1993        -6956.0         0.07
1994        -6643.0         0.07
1995        -7128.0         0.07
1996        -7209.0         0.06
1997       -11652.0         0.07
1998       -12730.0         0.08
1999       -10849.0         0.06
2000        -8446.0         0.04
2001        -9989.0         0.05
2002       -11437.0         0.06
2003       -12859.0         0.05
2004       -11986.0         0.04
2005       -13839.0         0.04
2006       -15462.0         0.04
2007       -15387.0         0.04
2008       -19318.0         0.04
2009       -22491.0         0.07
2010       -26871.0         0.07
2011       -30975.0         0.07
2012       -34271.0         0.08
2013       -33669.0         0.08
2014       -32952.0         0.08
2015       -26490.0         0.11
2016       -16163.0         0.08
2017       -15402.0         0.06
2018       -19574.0         0.07
2019       -24361.0         0.10
2020       -17282.0         0.10
2021       -12076.0         0.04
2022       -18407.0         0.05
2023       -21919.0         0.07

In [5]:
tax_df = cost_df [['TaxPaid']].abs()
cash_df = pd.read_csv(Cash_Data_Fy,index_col='FiscalYear')
tax_df['NetIncome'] = cash_df['NetIncome']
tax_df['TaxRate'] = round(tax_df['TaxPaid'] / tax_df['NetIncome'], 2)


tax_df

            TaxPaid  NetIncome  TaxRate
FiscalYear
1984         5070.0     5528.0     0.92
1985         4688.0     4870.0     0.96
1986         3196.0     5360.0     0.60
1987         2703.0     4840.0     0.56
1988         3124.0     5260.0     0.59
1989         2028.0     3510.0     0.58
1990         3170.0     5010.0     0.63
1991         2918.0     5600.0     0.52
1992         2477.0     4770.0     0.52
1993         2772.0     5280.0     0.52
1994         2704.0     5100.0     0.53
1995         3972.0     6470.0     0.61
1996         4406.0     7510.0     0.59
1997         7605.0    11732.0     0.65
1998         3939.0     8074.0     0.49
1999         3240.0     7910.0     0.41
2000        11075.0    17720.0     0.62
2001         8967.0    15320.0     0.59
2002         6499.0    11460.0     0.57
2003        11006.0    21510.0     0.51
2004        15911.0    25330.0     0.63
2005        23302.0    36130.0     0.64
2006        27902.0    39500.0     0.71
2007        29864.0    40610.0     0.74
2008        36530.0    45220.0     0.81
2009        15119.0    19280.0     0.78
2010        21561.0    30460.0     0.71
2011        31051.0    41060.0     0.76
2012        31045.0    44880.0     0.69
2013        24263.0    32580.0     0.74
2014        18015.0    32520.0     0.55
2015         5415.0    16150.0     0.34
2016          406.0     7840.0     0.05
2017         1174.0    19710.0     0.06
2018         9532.0    20840.0     0.46
2019         5282.0    14340.0     0.37
2020         5632.0   -22440.0    -0.25
2021         7636.0    23040.0     0.33
2022        20176.0    55740.0     0.36
2023        15429.0    36010.0     0.43